name: universiting
description: Meet new student in campus.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flutter_naver_map: ^0.10.5
  kakao_flutter_sdk: ^0.9.0
  flutter_svg: ^1.0.3
  firebase_core: ^1.16.0
  firebase_messaging: ^11.3.0
  http: ^0.13.4
  connectivity_plus: ^2.2.1
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  image_picker: ^0.8.4+11
  image_picker_for_web: ^2.1.6
  flutter_local_notifications: ^9.4.0
  flutter_spinkit: ^5.1.0
  pull_to_refresh: ^2.0.0
  flutter_keyboard_visibility: ^5.2.0
  modal_bottom_sheet: ^2.0.1
  flutter_datetime_picker: ^1.5.1
  cached_network_image: ^3.2.0
  flutter_svg_provider: ^1.0.3
  table_calendar: ^3.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/illustrations/

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUIT-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUIT-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SUIT-Heavy.ttf
          weight: 900
        - asset: assets/fonts/SUIT-Light.ttf
          weight: 300
        - asset: assets/fonts/SUIT-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUIT-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUIT-Thin.ttf
          weight: 100
